[info]
typeName = "folly::F14NodeSet<"
stub_template_params = [1,2,3]
ctype = "F14_SET"
header = "folly/container/detail/F14SetFallback.h"
ns = ["folly::F14NodeSet"]

# Old:
numTemplateParams = 1
replaceTemplateParamIndex = [1, 2]
allocatorIndex = 3

[codegen]
decl = """
template <typename Key, typename Hasher, typename KeyEqual, typename Alloc>
void getSizeType(const %1%<Key, Hasher, KeyEqual, Alloc> &container, size_t& returnArg);
"""

func = """
template <typename Key, typename Hasher, typename KeyEqual, typename Alloc>
void getSizeType(const %1%<Key, Hasher, KeyEqual, Alloc> &container, size_t& returnArg)
{
    size_t memorySize = container.getAllocatedMemorySize();
    SAVE_SIZE(sizeof(%1%<Key, Hasher, KeyEqual, Alloc>) + memorySize);

    SAVE_DATA(memorySize);
    SAVE_DATA(container.bucket_count());
    SAVE_DATA(container.size());

    // The double ampersand is needed otherwise this loop doesn't work with vector<bool>
    for (auto&& it: container) {
        getSizeType(it, returnArg);
    }
}
"""
