[info]
typeName = "folly::IOBufQueue"
matcher = "^folly::IOBufQueue$"
numTemplateParams = 0
ctype = "FOLLY_IOBUFQUEUE_TYPE"
header = "folly/io/IOBufQueue.h"
ns = ["folly::IOBufQueue"]
replaceTemplateParamIndex = []
# allocatorIndex = 0

[codegen]
decl = """
void getSizeType(const %1% &container, size_t& returnArg);
"""

func = """
void getSizeType(const %1% &container, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%));

    const IOBuf *head = container.front();
    SAVE_DATA((uintptr_t)head);
    if (head && pointers.add((uintptr_t)head)) {
        SAVE_DATA(1);
        getSizeType(*head, returnArg);
    } else {
        SAVE_DATA(0);
    }
}
"""
