[info]
typeName = "std::optional<"
ctype = "OPTIONAL_TYPE"
header = "optional"
ns = ["namespace std"]

# Old:
numTemplateParams = 1

[codegen]
decl = """
template<typename T>
void getSizeType(const %1%<T> &container, size_t& returnArg);
"""

func = """
template <typename T>
void getSizeType(const %1%<T>& container, size_t& returnArg) {
  if (container) {
    SAVE_SIZE(sizeof(%1%<T>) - sizeof(T));
    SAVE_DATA(true);
    getSizeType(*container, returnArg);
  } else {
    SAVE_SIZE(sizeof(%1%<T>));
    SAVE_DATA(false);
  }
}
"""
