[info]
typeName = "apache::thrift::detail::isset_bitset<"
ctype = "THRIFT_ISSET_TYPE"
header = "thrift/lib/cpp2/gen/module_types_h.h"
ns = ["apache::thrift::detail::isset_bitset"]

# Old:
numTemplateParams = 2
replaceTemplateParamIndex = []

[codegen]
decl = """
// DummyDecl %1%
"""
func = """
// DummyFunc %1%
"""
