[info]
typeName = "std::unique_ptr"
ctype = "UNIQ_PTR_TYPE"
header = "memory"
ns = ["namespace std"]

# Old:
## TODO what about Deleter (idx 1)?
numTemplateParams = 1
replaceTemplateParamIndex = []

[codegen]
decl = """
template<typename T, class Deleter>
void getSizeType(const %1%<T,Deleter> &s_ptr, size_t& returnArg);
"""

func = """
template<typename T, class Deleter>
void getSizeType(const %1%<T,Deleter> &s_ptr, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%<T,Deleter>));

    if constexpr (!std::is_void<T>::value) {
        SAVE_DATA((uintptr_t)(s_ptr.get()));

        if (s_ptr && pointers.add((uintptr_t)(s_ptr.get()))) {
            SAVE_DATA(1);
            getSizeType(*(s_ptr.get()), returnArg);
        } else {
            SAVE_DATA(0);
        }
    }
}
"""
